Repository jahirfiquitiva/Blueprint, pull requests merged in 2018-07, with the labels that each got.

#102 New Crowdin translations
  library/src/main/res/values-ar-rSA/translatable_strings.xml
  library/src/main/res/values-hr-rHR/translatable_strings.xml
  library/src/main/res/values-it-rIT/translatable_strings.xml
  library/src/main/res/values-pt-rBR/translatable_strings.xml
  library/src/main/res/values-vi-rVN/translatable_strings.xml
Labels: Priority: Low, Status: Accepted, Type: Enhancement

#103 Stop using MaterialDrawer
  app/proguard-rules.pro
  dependencies.gradle
  library/build.gradle
  library/proguard-rules.pro
  library/src/main/kotlin/jahirfiquitiva/libs/blueprint/helpers/extensions/Context.kt
  library/src/main/kotlin/jahirfiquitiva/libs/blueprint/ui/activities/BaseBlueprintActivity.kt
  library/src/main/kotlin/jahirfiquitiva/libs/blueprint/ui/activities/DrawerBlueprintActivity.kt
  library/src/main/kotlin/jahirfiquitiva/libs/blueprint/ui/activities/HelpActivity.kt
  library/src/main/res/layout/activity_w_drawer.xml
  library/src/main/res/layout/drawer_header.xml
  library/src/main/res/menu/menu_drawer.xml
  library/src/main/res/raw/notices.xml
  library/src/main/res/values/colors.xml
  library/src/main/res/values/dimens.xml
  library/src/main/res/values/ids.xml
  library/src/main/res/values/styles.xml
  library/src/main/res/values/themes.xml
Labels: Priority: High, Status: Accepted, Type: Enhancement

#104 New Crowdin translations
  library/src/main/res/values-hu-rHU/translatable_strings.xml
  library/src/main/res/values-ko-rKR/translatable_strings.xml
  library/src/main/res/values-vi-rVN/translatable_strings.xml
Labels: Status: Pending

#105 New Crowdin translations
  library/src/main/res/values-cs-rCZ/translatable_strings.xml
  library/src/main/res/values-es-rES/translatable_strings.xml
  library/src/main/res/values-nl-rNL/translatable_strings.xml
  library/src/main/res/values-ru-rRU/translatable_strings.xml
Labels: Priority: Low, Status: Accepted, Type: Enhancement

#116 Add support for Lawnchair
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/launchers.xml
  library/src/main/kotlin/jahirfiquitiva/libs/blueprint/helpers/extensions/Launchers.kt
  library/src/main/res/drawable-nodpi/ic_lawnchair.png
  library/src/main/res/values/colors.xml
  library/src/main/res/values/launchers.xml
Labels: Status: Pending

#112 New Crowdin translations
  library/src/main/res/values-cs-rCZ/translatable_strings.xml
  library/src/main/res/values-hr-rHR/translatable_strings.xml
  library/src/main/res/values-pl-rPL/translatable_strings.xml
  library/src/main/res/values-ru-rRU/translatable_strings.xml
  library/src/main/res/values-sh-rHR/translatable_strings.xml
  library/src/main/res/values-tr-rTR/translatable_strings.xml
Labels: Status: Pending
