Repository jahirfiquitiva/Blueprint, pull requests merged in 2020-07, with the labels that each got.

#226 New Crowdin updates
  library/src/main/res/values-cs-rCZ/translatable_strings.xml
  library/src/main/res/values-it-rIT/translatable_strings.xml
Labels: Status: Needs Info, Status: Stale

#232 Fix Extension Function Import (1/2)
  app/src/main/kotlin/dev/jahir/blueprint/app/NotificationService.kt
Labels: Priority: Medium

#233 Fix Extension Function Import (2/2)
  app/src/main/kotlin/dev/jahir/blueprint/app/NotificationService.kt
Labels: Priority: Medium

#234 Improve App Bundle File Naming (1/2)
  app/build.gradle
Labels: Priority: Low

#235 Improve App Bundle File Naming (2/2)
  app/build.gradle
Labels: Priority: Low

#238 New Crowdin updates
  library/src/main/res/values-in-rID/translatable_strings.xml
Labels: Status: Needs Info
